### ISSUE TITLE
Extend Visualizer to render Patterns

### ISSUE THREAD

**Issue by aidanm3341** [finos-labs/architecture-as-code#100]
The Visualizer currently only renders instantiations of patterns.
It should also render a pattern in the same way to ease the pattern development process.

**Comment by aidanm3341** [comment]
As a general approach to this, I am thinking of just reusing the CLI's `generate` functionality to take a pattern, turn it into an instantiation and then use the existing logic to visualise an instantiation. I don't see any reason why this shouldn't work, but let me know if anyone disagrees

**Comment by rocketstack-matt** [comment]
Does this fulfil what we need? I could lean either way on this, but if I'm viewing a pattern don't I want to see the actual parts I need to update visually differentiated from a pattern? 

@jpgough-ms any thoughts?

**Comment by aidanm3341** [comment]
I've done it this way for now as a starting point, so that it at least renders _something_ when you give it a pattern - but it's definitely open to modification if we want to capture more information

**Comment by jpgough-ms** [comment]
@rocketstack-matt I think this is a good first pass at this and it is helpful during the build process. I think we close this for now and raise any enhancements from how this is used.
