### ISSUE TITLE
Composable Architecture References

### ISSUE THREAD

**Issue by jpgough-ms** [finos-labs/architecture-as-code#111]
## Feature Request

Some patterns do not supply all the details for a given node within an architecture and indeed the node may be implemented in different ways by different pattern instantiations.  

### Description of Problem:

It would be good to provide a mechanism for a pattern instantiations to supply the implementation detail in additional CALM files. This could be something like:

```json
{
  "interfaces": [
    {
      "unique-id": "producer-ingress",
      "host": "{{ INGRESS_HOST }}",
      "port": -1
    }
  ],
  "node-type": "system",
  "name": "General API Producer",
  "description": "The API Producer serving content",
  "unique-id": "api-producer",
  "detailed-architecture": {
       "$ref": "api-producer.json"
   }
},
```

Having this feature (with interfaces) will enable us to create composable patterns within CALM.

@rocketstack-matt

**Comment by rocketstack-matt** [comment]
I really like this idea, it gives us the ability to drill in and out of architectures and provides the mechanism we wanted to enable us to represent what would be different levels in C4 without polluting a single model.

**Comment by jpgough-ms** [comment]
After a discussion with @rocketstack-matt I have created a proposed schema change in #132. This is a nice way of defining the additional node, however it comes with one architectural sticking point that the pattern and `detailed-architecture` node would need to use the same schema version. This could become problematic.

We will need to review how we might approach this with a view to make the `detailed-architecture` support a different version of the CALM schema

**Comment by rocketstack-matt** [comment]
What is it we actually want to achieve with this reference?

I think what we're trying to achieve is to enable different systems (or indeed subsystems within a complex system) to be linked so we can split what would be an unmanageable documentation process into something that provides 'right sized' views and enables the consumer (human or tool) to be able to navigate from one to the other.

If this is the case do we need to do anything other than specify the URI of an implementation? Ideally we would be able to provide a reusable repository mechanism for organisations to store their architecture implementations (and patterns) but assuming the referenced URI is findable then the human or tool could navigate and continue their journey.

Could we therefore simply make this a string?

**Comment by jpgough-ms** [comment]
In #132 we created a PR with a self referential schema validation, this could potentially cause multiple issues:

* It could pin the version of the calm together with the further detailed-architecture. This had the potential to be awkward to maintain pattern instantiations and the linked more detailed architectures 
* Referenced architectures might not be available in all situations 

Instead we will create a soft reference, which for the purpose of this issue will be a string property. Our tooling can then add a flag to understand the optional `detailed-architecture` node and follow the reference and validate independently against that version of the calm schema. Given the nature of calm, this might require a fork to execute a different context and command.
