### ISSUE TITLE
Publish visualizer to npm

### ISSUE THREAD

**Issue by rocketstack-matt** [finos-labs/architecture-as-code#126]
## Feature Request
Publish the visualizer program to npm.
* Required to enable other programs (such as the CLI to consume without tar bundle

**Comment by grahampacker-ms** [comment]
I believe this is no longer required as the visualizer has been moved into the CLI
@rocketstack-matt @aidanm3341

**Comment by rocketstack-matt** [comment]
I believe you're correct. Will close.
