### ISSUE TITLE
Validation Finds All Issues in a Pattern and Pattern Instantiation

### ISSUE THREAD

**Issue by jpgough-ms** [finos-labs/architecture-as-code#138]
### Description of Problem:

Running the `generate` and `validate` commands can detect problems in the schemas, however it fails at the first encountered problem. It would be good to see all the failures so that I can fix my problems in one go.

**Comment by rocketstack-matt** [comment]
I think we need to change the instantiation options. Looking at https://github.com/finos-labs/architecture-as-code/blob/478f07d14aa818050245375960f0b7183e51a85b/cli/src/commands/validate/validate.ts#L15

would become 
```typescript
const ajv = new Ajv2020({ strict: false, allErrors: true });
```

**Comment by lbulanti-ms** [comment]
@jpgough-ms I merged a pr to enable the allErrors mode, I tested it locally and it worked. Let me know if you have a chance to try it out
