### ISSUE TITLE
Concept of an External Node

### ISSUE THREAD

**Issue by jpgough-ms** [finos-labs/architecture-as-code#17]
### Description of Problem:

When describing architecture we often refer to the system under review to define what is in scope for review. In complex environments, we do not always want to review systems that are on the peripheral. It would be good to mark these are external nodes.

### Potential Solutions:

- Introduce an external nodes array
- Create an optional property on node for external

@rocketstack-matt would be good to get your input

**Comment by Budlee** [comment]
I personally like the idea of a flag on a node to state if it is external

**Comment by jpgough-ms** [comment]
@Budlee and @rocketstack-matt I'm wondering if we add the fact something is external to the `detailed-architecture` node proposed in #137 

e.g.

```json
"detailed-architecture": {
    "type": "string",
    "external": "boolean"
},
```

Neither field is mandatory, so we would be able to define:
- A node is external
- A node is external and here is a reference to the architecture
- A node as a more detailed architecture and it's not external, I just can't fit complexity in a single file

**Comment by rocketstack-matt** [comment]
We have a set of pre-defined node-type's

```json
"node-type-definition": {
      "enum": [
        "actor",
        "system",
        "service",
        "database",
        "internal-network",
        "ldap",
        "webclient"
      ]
    }
```

Whilst I think we need to review some of these types, which is a different conversation, doesn't this give us what we need without adding an extra flag?

Taking `system` as the easy case . . . a system node must be external.

Other node-types such as `actor` simply can't have a detailed architecture and we should update the schema to reflect this.

What I think we need to add is an additional node-type-definition along the lines of `sub-system`, this would allow us to arbitrarily group up sections of a system into separate documents.

**Comment by jpgough-ms** [comment]
I think the reason I was requesting this feature has now been resolved by the introduction of `detailed-architecture` #137 has resolved. I am going to close this issue and we can re-open if we have a different use case that would need this
