### ISSUE TITLE
Visualising Architecture as Code

### ISSUE THREAD

**Issue by jpgough-ms** [finos-labs/architecture-as-code#19]
### Description of Problem:

Once the scope of an architecture reaches multiple nodes and multiple relationships it can be difficult to visualise what the YAML/JSON represents. 

As an author of patterns or architecture, I would like to be able to see my architecture progress as I build out my nodes and relationships, so that I can understand bigger models.

As a developer or reviewer of an architecture, I would like to be able to visualise an architecture, so that I don't have to attempt to build up an understanding of JSON/CALM. 

### Potential Solutions:

- A visualisation in a web view/Javascript 
- An IDE plugin would be great in the longer term

**Comment by matthewgardner** [comment]
Would it be useful to general the PUML file, or do we think something more interactive would be better?

**Comment by rocketstack-matt** [comment]
@matthewgardner I think we're planning on a C4 converter as well as this - plan with this would be to evolve to a realtime IDE Plugin
