### ISSUE TITLE
Add a GitHub action to run Spectral validation on CALM specification changes against existing patterns

### ISSUE THREAD

**Issue by rocketstack-matt** [finos-labs/architecture-as-code#35]
### Description of Problem:
We now have a Spectral validator thanks to @willosborne in #28 - ideally this would be setup to run when the CALM specification changes to confirm patterns and samples are still valid, or conversely if the patterns or samples change they should run to confirm they're still valid per the existing spec.

**Comment by rocketstack-matt** [comment]
@willosborne are we happy to close this issue now?

**Comment by willosborne** [comment]
@rocketstack-matt No, this is not working - PR was not ready when it was merged. I thought I had marked the PR as a draft, my bad.

The validation works, but it can't mark itself as having failed due to permissions issues and thus always succeeds.

**Comment by willosborne** [comment]
Going to try a new PR that does this manually, without using the Stoplight action.

**Comment by willosborne** [comment]
Currently we have spectral rules to check instantiations, nothing on the patterns themselves.
Proper JSON schema validation will be a much more valuable inspection to run.

**Comment by jpgough-ms** [comment]
@willosborne is this working now?

**Comment by rocketstack-matt** [comment]
We will change approach to integrate actions validation with the new CLI - @willosborne please link to a new issue detailing that implementation then close this issue.

**Comment by willosborne** [comment]
Currently we have a basic version of this running. This work will be extended in issue #97 - so closing issue for now.
