### ISSUE TITLE
Sample manifest references missing node

### ISSUE THREAD

**Issue by rocketstack-matt** [finos-labs/architecture-as-code#37]
### Steps to Reproduce:
 1. See file calm/samples/api-gateway-implementation.json
 2. There is a relationship to 'idp' which is not a defined node

### Expected Result:
Relationships should only reference real nodes

### Actual Result:
You can see the resulting visualisation here:
![Screenshot 2024-03-01 at 11 34 54](https://github.com/finos-labs/architecture-as-code/assets/66839492/338c4012-4ba2-4897-866a-0b6ed0a04698)

### Environment:
main branch

**Comment by rocketstack-matt** [comment]
@jpgough-ms can you take a look at this please.

**Comment by Budlee** [comment]
This looks like it was resolved here:
https://github.com/finos-labs/architecture-as-code/blob/main/calm/pattern/api-gateway.json#L99
