### ISSUE TITLE
Composable Patterns using a Pattern Interface

### ISSUE THREAD

**Issue by jpgough-ms** [finos-labs/architecture-as-code#48]
### Description of Problem:

In #11 we modified CALM to be a [JSON Meta-Schema](https://json-schema.org/specification#meta-schemas), which enabled the creation of patterns and the instantiation of patterns. 

In #11 we presented the idea of an API Gateway pattern, which had the nodes: `API Consumer`, `API Producer`, `API Gateway`, and `IDP`. In this model, the `API Producer` was modelled as a `Node`. However, in reality the `API Producer` could be a series of connected microservices, connect to a database etc. 

Based on the [API Gateway Pattern](calm/pattern/api-gateway.json) the `API Producer is connected to using a `host` and `port`. If we could specify a node to have an optional external reference to a CALM compliant JSON, we could model patterns that have a variety of possible node level implementations. 

### Potential Solutions:

Create the concept of an interface which defines the hand-off/boundary between two patterns, allowing patterns to be composable or contained within other patterns.

**Comment by rocketstack-matt** [comment]
Ok, sounds like you're seeing the same issues as @Budlee reported in #47

**Comment by rocketstack-matt** [comment]
Link to #17

**Comment by rocketstack-matt** [comment]
Some thoughts / comments for discussion later:
* What we see in the API Gateway pattern shows a system level diagram of interactions, would be similar to System Context Diagram in C4.
* Each of these systems should theoretically have a full CALM model describing them.
* Currently we model the purpose of a node and the type of relationship that connects them, but we don't model the actual interface a node exposes, other than where we have added them as additional properties in the [api-gateway](https://github.com/finos-labs/architecture-as-code/blob/main/calm/pattern/api-gateway.json) pattern.
* Interfaces obviously need to exist for any software component to speak to another, this could be a host/port, a file share, a message queue, etc.
* Where do we think the interfaces should be captured on nodes / relationships / both? My initial thinking leans towards both, nodes should enumerate the interfaces they support and relationships should specify which interface they are connecting; this could be done by specifying the details in two places or we could add an explicit ID to an interface and reference the interface in the relationship?
* The validator should ensure that only declared interfaces are defined in relationships (error if they don't). It could also warn if a node exposes an interface which is not then used (should we add an ignore mechanism to document that the architect knows they are exposing an unreferenced port)?
* Assuming we agree interfaces exist, and we should be able to mark specific interfaces as external then those interfaces should also be referenced in the system level architectures with an explicit reference into the internal architecture.

**Comment by yt-ms** [comment]
There's a variant of the "Relationship is the interface" where the interface becomes again a defined node (similar to the difference between "Embedded interface in node" and "Interface as a node with an integral relationship to the service node".

But I agree that logically the interface "belongs" to the service that provides it so I'm veering away from the relationship-based versions.  Another point on that is that the interface exists even if nothing is connected to it (therefore there are no relationships yet).

**Comment by yt-ms** [comment]
> The more I look at these options, I think either embedded or as a node with integral relationship are the only real options. I think the others end up with us needing to replicate the interface details in multiple places if the interface is used more than once (e.g. multiple consumers connecting on the same port).

The two are semantically equivalent, so the trade-off is simplicity of authoring (the raw JSON/YAML) in the embedded one vs a less complex model to process systematically with the integral relationship.  I think I'm leaning towards the latter.

**Comment by rocketstack-matt** [comment]
Agreed, it also means where we refer to an interface at different levels (i.e. system to system) then we don't need to replicate the details . . . if the details are on the relationship we would have to repeat them and it would be harder to validate that the relationship at the system level match an existing relationship at a service level, which they must.

**Comment by rocketstack-matt** [comment]
Yes, I don't see any issue with that alternative.

**Comment by SlavaVedernikov** [comment]
Hi all,

Great to see others trying to solve the same problem :)
I'm gutted that I missed the opportunity to attend the Onsite Accelerator in London on 12 March..!

I'm working on [C4InterFlow](https://github.com/SlavaVedernikov/C4InterFlow) - Architecture as Code (AaC) framework.
It supports expressing Application/Software Architecture in **C#**, **YAML** and **JSON**.

Here is how the same scenario would look in JSON:

```json
{
    "NodesAndInterfacesExample": {
        "SoftwareSystems": {
            "ServiceA": {
                "Description": "The service that is going to connect",
                "Interfaces": {
                    "InterfaceToServiceB": {
                        "Protocol": "TCP, Port 8080",
                        "Flow": {
                            "Flows":[
                                {
                                    "Type": "Use",
                                    "Expression": "NodesAndInterfacesExample.SoftwareSystems.ServiceB.Interfaces.UsefulRestService"
                                }
                            ]
                        }
                    }
                }
            },
            "ServiceB": {
                "Description": "The service that is exposing an endpoint",
                "Interfaces": {
                    "UsefulRestService": {
                        "Protocol": "TCP, Port 8080"
                    }
                }
            }
        }
    }
}
```

...and here is YAML equivalent:

```yaml
NodesAndInterfacesExample:
  SoftwareSystems:
    ServiceA:
      Description: The service that is going to connect
      Interfaces:
        InterfaceToServiceB:
          Protocol: TCP, Port 8080
          Flow:
            Flows:
            - Type: Use
              Expression: ServiceB.Interfaces.UsefulRestService
    ServiceB:
      Description: The service that is exposing an endpoint
      Interfaces:
        UsefulRestService:
          Protocol: TCP, Port 8080
```
The **C4InterFlow** framework comes with a **CLI** that generates diagrams from AaC for different **viewpoints** - combinations of **Scope**, **Level of Details** and **Diagram Type*

Here is an example for this scenario:
![image](https://github.com/finos-labs/architecture-as-code/assets/19991188/a740c45e-2519-4b90-b08c-537e7cec9544)

I like what you are doing, and I think I can add value... How can I get involved..?

**Comment by rocketstack-matt** [comment]
Hi @SlavaVedernikov - nice to meet you!

Our Working Group meets the fourth Tuesday of every month, normally at 16:00 although this month it is 15:00 because of the clocks having already moved in the US, you can see the full FINOS community calendar [here](https://www.finos.org/calendar)

We are part of the [DevOps Automation Special Interest Group](https://devops.finos.org/) so confusingly our meeting agendas / minutes are currently in a separate repo, you can find them [here](https://github.com/finos/devops-automation/issues?q=is%3Aissue+label%3Aarchitecture-as-code+).

Would you be able to attend our call on 23rd March, happy to give you a slot on the agenda to show what you've been working on and see what we can do together?

We're also looking at trying to arrange a hack-day at some point in April.

**Comment by SlavaVedernikov** [comment]
Hi @rocketstack-matt - nice to meet you too :)

Yes, I can join the call on 26th March @ 15:00, thanks.
Also, happy to share what I've been working on.

**Comment by jpgough-ms** [comment]
With #106 we have decided to make interfaces optional on a relationship for now. If it was mandatory that would remove the ability to use CALM as a logical tool and mean that it is only a physical modelling tool.

We may need to consider whether we have a convention to mark what type of diagram this is

@rocketstack-matt, @yt-ms

**Comment by jpgough-ms** [comment]
@yt-ms @Budlee @rocketstack-matt @SlavaVedernikov 

We have created a prototype of interfaces, capturing the ideas of the accelerator and this issue in the 2024-04 folder. Please take a look and provide any feedback.

**Comment by jpgough-ms** [comment]
There are a couple of reference/structural issues that we are waiting for #73 to resolve

**Comment by jpgough-ms** [comment]
Pattern interface work is now complete and tooling is catching up to support the schema. The objective of this issue has been solved, I will close this and we can add any new issues that crop up for improvements/enhancements.
