### ISSUE TITLE
On-site Agenda

### ISSUE THREAD

**Issue by rocketstack-matt** [finos-labs/architecture-as-code#52]
## Agenda for LSEG On-site 2024-02-12

- [x] Recap of where we are, quick reminder of CALM, shows TraderX + API Gateway Pattern 
- [x] Demo of the visualisations (native CALM + C4) 
- [x] Open discussion on Composable Interfaces - https://github.com/finos-labs/architecture-as-code/issues/48 
- [x] Control Requirements - update on discussion
- [x] Pattern CLI Proposal #53 
- [x] Sub-working group leadership + commitment
- [x] Brain storming on features we want, live creation of Issues to track

**Comment by davidilles** [comment]
Is this where I comment that I attended yesterday? :)

**Comment by rocketstack-matt** [comment]
No :)

**Comment by davidilles** [comment]
Excellent:)

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
