### ISSUE TITLE
Pattern api-gateway.json does not conform to JSON Schema draft 2020-12 

### ISSUE THREAD

**Issue by lbulanti-ms** [finos-labs/architecture-as-code#74]
## Bug Report

The [api-gateway.json ](https://github.com/finos-labs/architecture-as-code/blob/main/calm/pattern/api-gateway.json) does not conform to the JSON Schema Draft 2020-12. As mentioned in the [release notes](https://json-schema.org/draft/2020-12/release-notes#changes-to-items-and-additionalitems) the `items` keyword changed to `prefixItems`. 

### Additional Context:
This issue has been discovered while trying out the AJV library to validate the pattern schema against the CALM meta-schema

**Comment by rocketstack-matt** [comment]
@lbulanti-ms do you mean that the core schema is wrong, which then correspondingly means the pattern is wrong or just the pattern? I think the former.

It would be great if you could show the code section and also what you ran to perform the validation if that is something that would be reproducible so that the person fixing the bug could validate they had done it correctly.

**Comment by lbulanti-ms** [comment]
While there are other known issues with the [core.json](https://github.com/finos-labs/architecture-as-code/blob/main/calm/draft/2024-03/meta/core.json) meta-schema(we are raising a separate issue), this particular issue refers to the section below which uses the `items` key instead of the `prefixItems` key.
```"properties": {
    "nodes": {
      "type": "array",
      "minItems": 3,
      "items": [
        {
          "$ref": "https://raw.githubusercontent.com/finos-labs/architecture-as-code/main/calm/draft/2024-03/meta/core.json#/defs/node",
          "properties": {
            "ingress-host": {
              "type": "string"
            },
            ...
```
To validate the schema I used the AJV library. I ran this command 
`ajv compile -s api-gateway.json -r core.json -r calm.json --spec=draft2020 --strict=false` (we are not sure if we want to use the strict mode, so I set that to false while testing)
The error I am getting is `schema api-gateway.json is invalid
error: schema is invalid: data/properties/nodes/items must be object,boolean`

I am planning to raise a PR to fix this issue.

**Comment by rocketstack-matt** [comment]
Thanks @lbulanti-ms so the issue you're looking at is in the pattern itself, but I think we have the same issue in the [core schema](https://github.com/finos-labs/architecture-as-code/blob/0c2fd64b267da1ebe12fb5efcbb06e066abf554c/calm/draft/2024-03/meta/core.json#L8) itself.

``` json
"properties": {
    "nodes": {
      "type": "array",
      "items": {
        "$ref": "#/defs/node"
      }
    },
    "relationships": {
      "type": "array",
      "items": {
        "$ref": "#/defs/relationship"
      }
    },
    "required": [
      "nodes",
      "relationships"
    ]
  }
```

Do you agree?

**Comment by lbulanti-ms** [comment]
@rocketstack-matt yes correct. I agree with you. The [properties section](https://github.com/finos-labs/architecture-as-code/blob/main/calm/draft/2024-03/meta/core.json#L5) of the [core schema](https://github.com/finos-labs/architecture-as-code/blob/main/calm/draft/2024-03/meta/core.json) seems to have a couple of issues. Thank you for pointing this out!
