### ISSUE TITLE
C4 Translator to handle multiple software systems

### ISSUE THREAD

**Issue by Budlee** [finos-labs/architecture-as-code#86]
## Feature Request
The C4 Translator should handle multiple software systems from the calm specification

### Description of Problem:
Currently the C4 Translator does not work with multiple software systems defined in the CALM spec. I want to be able to represent in a C4 Format multiple systems.

**Comment by rocketstack-matt** [comment]
@Budlee is this resolved now? Should this issue be closed?

**Comment by Budlee** [comment]
Yes it should be. Let me close it
