### ISSUE TITLE
Unify CLI validation output from Spectral and AJV, support JUnit test output

### ISSUE THREAD

**Issue by willosborne** [finos-labs/architecture-as-code#98]
### Description of Problem:
Currently spectral and ajv output in different formats. We want to be able to consume both validations in a single go - they should be output together as a single data structure.
This also needs to be in a format that a CI pipeline can consume. We will need at least JUnit as this is the standard, but GH actions gives us very nice in-line comments on a PR so this may be valuable

### Potential Solutions:
- Take both outputs and fit into single data structure
- Spectral already supports JUnit test result format - re-use this feature
- Potentially use a library to easily add support for GH actions format, JUnit, etc.

**Comment by lbulanti-ms** [comment]
I had a look at the spectral output and at the json schema validation output and I tried to merge them into a single object.

This is an example of Spectral output:
```
{
        "code": "referenced-interfaces-defined",
        "message": "'producer-ingress' does not refer to the unique-id of an existing interface.",
        "path": [
            "relationships",
            "2",
            "relationship-type",
            "connects",
            "destination",
            "interface"
        ],
        "severity": 0,
        "range": {
            "start": {
                "line": 76,
                "character": 25
            },
            "end": {
                "line": 76,
                "character": 43
            }
        }
    }
```

This is an example of Json Schema Validation output:
```
{
        "instancePath": "/nodes/0/interfaces/0/port",
        "schemaPath": "https://raw.githubusercontent.com/finos-labs/architecture-as-code/main/calm/draft/2024-04/meta/interface.json#/defs/host-port-interface/properties/port/type",
        "keyword": "type",
        "params": {
            "type": "integer"
        },
        "message": "must be integer"
}
```

This is a first proposal of the single output:

```
// spectral 
{
    "code": "referenced-interfaces-defined",
    "severity": "error",
    "message": "'producer-ingress' does not refer to the unique-id of an existing interface.",
    "path": "relationships.2.relationship-type.connects.destination.interface"  
}

// json schema
{
    "code": "json-schema",
    "severity": "error",
    "schemaPath": "https://raw.githubusercontent.com/finos-labs/architecture-as-code/main/calm/draft/2024-04/meta/interface.json#/defs/host-port-interface/properties/port/type",
    "message": "must be integer",
    "path": "nodes.0.interfaces.0.port",
}

```

In the json-schema example I am thinking to hardcode "json-schema" as the `code` and add an additional field for the `schemaPath`.

I would like some feedback on this one before starting to write code. @willosborne @aidanm3341 @grahampacker-ms @jpgough-ms @rocketstack-matt

**Comment by aidanm3341** [comment]
I think this would be a big improvement, and your suggestion to use 'json-schema' as the code makes sense to me. I wonder if there is some way to get the line number from a json file given a jsonpath... I couldn't find anything from a quick search but it would be a nice feature to have in the error output.  

The message in the json schema example isn't great with just "must be an integer". It would be good if that also included the name of the field that must be an integer

**Comment by lbulanti-ms** [comment]
> I think this would be a big improvement, and your suggestion to use 'json-schema' as the code makes sense to me. I wonder if there is some way to get the line number from a json file given a jsonpath... I couldn't find anything from a quick search but it would be a nice feature to have in the error output.
> 
> The message in the json schema example isn't great with just "must be an integer". It would be good if that also included the name of the field that must be an integer

* I am going to have a look as well about getting the line number from the jsonpath. Spectral already provide that information

* Work out the property name might be a bit tricky because in the example I previously shared the field `port` is specified in the `path` but in the example I am sharing next the field is specified in the `params` section: 
```
    {
        "instancePath": "/nodes/2/interfaces/0",
        "schemaPath": "interface.json#/defs/interface-type/required",
        "keyword": "required",
        "params": {
            "missingProperty": "unique-id"
        },
        "message": "must have required property 'unique-id'"
    }
```
@aidanm3341 what do you think about this inconsistent scenario?

**Comment by lbulanti-ms** [comment]
> yeah seems a little awkward. I think it's not too big a deal at the moment as all the information is provided if you look at the whole object anyway. It could be a future enhancement, I wouldn't worry about that now then.

@aidanm3341 We should probably still print the default output from ajv and spectral when the `-v` flag is passed

**Comment by rocketstack-matt** [comment]
I like the approach - I would suggest get it in and we can then see how easy / hard it is to figure out where the issue is without either line number or field name.

**Comment by rocketstack-matt** [comment]
Seems sensible to me.
